# Start from upgraded ROS1 Noetic CPU base image
# Install LIO-SAM and Livox ROS Driver
FROM ros1-noetic-cpu-upgraded AS ros1-noetic-cpu-lio-sam-final

# Set up catkin workspace
WORKDIR /catkin_ws

# Clone and build Livox SDK2
RUN mkdir -p /livox_sdk \
    && cd /livox_sdk \
    && git clone https://github.com/Livox-SDK/Livox-SDK2.git \
    && cd Livox-SDK2 \
    && git checkout v1.2.5 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j 10 \
    && make install

# Clone, build and install Livox ROS Driver
RUN mkdir -p /livox_sdk/catkin_ws/src \
    && cd /livox_sdk/catkin_ws/src \
    && git clone https://github.com/Livox-SDK/livox_ros_driver2.git \
    && cd livox_ros_driver2 \
    && git checkout 1.2.4 \
    && source /opt/ros/noetic/setup.bash \
    && ./build.sh ROS1

# Clone LIO-SAM and apply the necessary tweaks for Noetic
# NOTE: solution to FLANN serialization issue was adapted from:
# https://github.com/mariusmuja/flann/issues/214
RUN mkdir -p /catkin_ws/src \
    && cd /catkin_ws/src \
    && git clone https://github.com/TixiaoShan/LIO-SAM.git \
    && cd LIO-SAM \
    && git checkout 0be1fbe6275fb8366d5b800af4fc8c76a885c869 \
    # Replace opencv/cv.h with opencv2/opencv.hpp
    && sed -i 's/#include <opencv\/cv.h>/#include <opencv2\/opencv.hpp>/g' include/utility.h \
    # Update C++ standard from C++11 to C++14
    && sed -i 's/set(CMAKE_CXX_FLAGS "-std=c++11")/set(CMAKE_CXX_FLAGS "-std=c++14")/g' CMakeLists.txt \
    # Fix FLANN serialization issue by reordering includes (FLANN before OpenCV)
    && sed -i '/#include <pcl\/kdtree\/kdtree_flann.h>/d' include/utility.h \
    && sed -i 's/#include <opencv2\/opencv.hpp>/#include <pcl\/kdtree\/kdtree_flann.h>\n\n#include <opencv2\/opencv.hpp>/g' include/utility.h

# Build the catkin workspace
RUN source /opt/ros/noetic/setup.bash \
    && source /livox_sdk/catkin_ws/devel/setup.bash \
    && cd /catkin_ws \
    && catkin init \
    && catkin config --no-instal \
    && catkin build --start-with lio_sam

# Final stage with LIO-SAM and Livox
FROM ros1-noetic-cpu-lio-sam-final AS ros1-noetic-cpu-liosam-recording

RUN apt-get update && apt-get install -y \
    nlohmann-json3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy cpp_pubsub package to the catkin workspace (TODO: rename to bag2laz)
COPY ./ros_on_docker/cpp_pubsub_ros1/ /catkin_ws/src/cpp_pubsub/

# Rebuild the catkin workspace to include the cpp_pubsub package
RUN source /opt/ros/noetic/setup.bash \
    && source /livox_sdk/catkin_ws/devel/setup.bash \
    && source /catkin_ws/devel/setup.bash \
    && cd /catkin_ws \
    && git clone https://github.com/LASzip/LASzip.git ./src/cpp_pubsub/src/3rdparty/LASzip \
    && cd ./src/cpp_pubsub/src/3rdparty/LASzip \
    && git checkout 4aada844e87066533619bcf0abec32ebee7da5d7 \
    && cd /catkin_ws \
    && catkin build

# NOTE: LASzip 3.4.1 + 2Gb file size fix is required (all is in 3.4.4 too but interface changed)

# Source ROS workspace in .bashrc
# RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc \
#     && echo "source /catkin_ws/devel/setup.bash" >> ~/.bashrc

# Setup entrypoint
COPY ./ros_on_docker/ros1_cpu_entrypoint.sh /ros_entrypoint.sh
RUN chmod +x /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"] 